"""The two files that make a profile folder self-explanatory.

This data may be used for the rest of Kyle's life. Formats have to stay
readable in ten years by someone who is not us and cannot run this app.
CSV and JSON handle the machine side of that; these two files handle
the human side:

    CLAUDE.md   for a Claude session pointed at the folder cold — the
                layout, the metrics, the person, the ground rules.
    README.md   the same thing for a human — a clinician, a future
                collaborator, Kyle himself, or us in five years.

Both are generated, and both are safe to edit: regeneration only
replaces a file that still carries the generator's marker line at the
top *and* was written by an older version. Delete the marker and the
file is yours forever.
"""

from __future__ import annotations

import datetime as dt
import os
from typing import Optional

# v3 — 2026-08-09. The subject context was wrong: it described a
# symmetric bilateral transradial amputation. Kyle's left limb is a long
# transradial (an inch above the wrist bone), his right is at the elbow
# with no forearm at all. Every generated doc that still claims two
# equivalent forearms must be rewritten, which is what this bump does.
DOCS_VERSION = 3
MARKER_PREFIX = "<!-- generated by Factum"
MARKER = (f"{MARKER_PREFIX} (docs v{DOCS_VERSION}) — edit freely; "
          f"delete this line and it will never be regenerated -->")


def _should_write(path: str) -> bool:
    """Write if absent, or if ours and stale. Never clobber human edits."""
    if not os.path.exists(path):
        return True
    try:
        with open(path, "r", encoding="utf-8") as f:
            first = f.readline().strip()
    except OSError:
        return False
    if not first.startswith(MARKER_PREFIX):
        return False          # someone removed the marker — hands off
    return first != MARKER    # ours, but from an older version


def _write(path: str, text: str) -> bool:
    if not _should_write(path):
        return False
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return True


# ================================================================= CLAUDE.md


def claude_md(profile_name: str, profile_type: str = "subject",
              subject_context: str = "") -> str:
    context = subject_context.strip() or DEFAULT_SUBJECT_CONTEXT
    return f"""{MARKER}
# CLAUDE.md — profile `{profile_name}`

You are looking at a Factum profile folder: the complete record of one
person's surface nerve/muscle recordings. Read this file first; it
explains the layout, the metrics, and the situation, so you can work
from the data without needing anything else.

## Who this is

{context}

## What the hardware is

A Mudra Band on the forearm: three surface electrodes sampling at
about 1000 Hz, delivered as SNC (surface nerve conduction) data over a
local WebSocket. Channel order is fixed everywhere in this project:

| Column | Electrode |
|--------|-----------|
| `ch1`  | ulnar     |
| `ch2`  | median    |
| `ch3`  | radial    |

Values are raw, in the range -1..+1, exactly as the Mudra host
delivered them. **No filtering is applied on write** — every probe CSV
says `filters: none`. If a recording is filtered in future, that
header field is where it will say so.

The band's stock gestures (tap, pinch, swipe, point, rotate) are all
defined by fingers touching or a hand rotating, and its pressure
feature measures literal thumb-to-finger contact. None of that is
anatomically available here. That is why everything in this folder is
his own signal, discovered from scratch — **there is no fixed movement
list anywhere in this project.**

## Folder layout

```
{profile_name}/
    profile.json          name, type, notes, active arm, open sessions
    CLAUDE.md             this file
    README.md             the same thing for a human reader
    placement/            photos and marks for repeatable band placement
    left/  right/         one sub-tree per arm — they are independent
        placement_notes.md    timestamped log of where the band sat
        sessions/
            2026-08-14_1430/          one visit, one arm
                session.json          date, location, who was present,
                                      notes, battery %, charger y/n
                session_notes.md      free-text running log, timestamped
                probes/
                    001_rest_1430.csv
                    002_curl-ring-finger_1433.csv
                probes.json           manifest: metadata + metrics for
                                      every probe in the session
                analysis.json         full analysis, machine-readable
                REPORT.md             the same analysis, for humans
                ANALYSIS_PROMPT.md    ready-made prompt for this session
```

Sessions are **append-only**. A session folder is never overwritten and
never renamed, because comparing the same movement across days is how
we detect drift in placement, skin condition and fatigue.

## What a probe is

One short recording of one attempted movement, named by him in his own
words ("curl ring finger", "the twitchy one"). Default 30 seconds.
Each file opens with a self-describing comment header:

```
# profile: {profile_name}
# arm: left
# session: 2026-08-14_1430
# probe: curl ring finger
# started: 2026-08-14T14:33:07
# duration_s: 30
# sample_rate_hz: 1000
# effort: moderate
# fatigue: some
# his_confidence: 4
# placement: 3 fingers below elbow crease, ulnar side, mark A
# filters: none
# notes: felt distinct to him
timestamp,ch1,ch2,ch3
```

`timestamp` is milliseconds since the start of that probe.
`status: incomplete` in a header means the recording was interrupted —
the data before that point is still valid and still worth using.

Every session starts with a **rest** probe. Baseline drifts with
placement, skin and fatigue, so every other measurement in a session is
relative to that session's own rest recording. A comparison against a
different day's baseline is meaningless.

## The metrics

{metric_glossary_md()}

## Ground rules of this project

- **CSV and JSON only** for data. No pickle, no npz. A fitted
  classifier `.pkl` is acceptable but must always be shadowed by a JSON
  metrics file beside it.
- **Everything lives under a profile.** Nothing is written outside a
  profile folder.
- **Consistency and low effort beat raw signal strength.** A weak
  movement performed identically every time is more useful than a
  strong one that varies. A movement that tires him will not survive
  daily use, however good its numbers look.
- **The goal is the smallest set of reliably separable signals**, not
  the largest.
- Raw sample arrays are never sent to an API. Work from `probes.json`,
  `analysis.json` and `REPORT.md`; open a CSV only when you need a
  specific number from it.

## If you are asked to analyse a session

Start with that session's `REPORT.md`, then `analysis.json` for the
numbers behind it, then `probes.json` for per-probe metadata. Each
session also has an `ANALYSIS_PROMPT.md` written for exactly this
purpose. Useful questions to answer: which probes should be promoted
into a training set, which pairs will be confused, what changed since
the last session, and what specifically to try next.
"""


DEFAULT_SUBJECT_CONTEXT = """Kyle, a bilateral upper-limb amputee. **The two sides are different,
and it changes what each one can do:**

- **Left — amputated about an inch above the wrist bone**, so the wrist
  bone is gone. A long transradial residual limb: nearly the whole
  forearm remains, and with it the finger and wrist muscle bellies.
  This is the working arm and the only one a forearm band fits.
- **Right — amputated at the elbow.** No forearm at all. A forearm band
  has nowhere to sit; only upper-arm muscle (biceps, triceps) remains,
  which carries no finger content. It can serve as a coarse extra
  switch, never as a second hand.

The movements recorded here are **attempted or phantom movements**, not
executed ones: there is no hand to move, and the signal comes from the
residual limb.

A helper puts the band on him, so repeatable placement is a first-class
concern rather than a detail. Placement is recorded as numbers —
millimetres from the elbow crease and degrees of rotation around the
limb — against a drawn limb in the app, written to `profile.json` and
mirrored into `placement_notes.md`. Every probe CSV carries the
placement in its header.

He cannot reliably operate a mouse or keyboard, which is why the app
that produced this data automates almost everything and asks for as
few clicks as possible. His own priority is using his iPhone; the PC
is the development platform.

`left/` and `right/` are separate sub-trees because the two limbs are
independent signal sources — but they are NOT equivalent sources. An
earlier version of this note claimed two limbs double the available
vocabulary. That was written before the amputation levels were known
and it is wrong: there is one forearm here."""


def metric_glossary_md() -> str:
    """Rendered from analysis.py so there is exactly one definition of each."""
    from analysis import METRIC_GLOSSARY, SCORING_EXPLANATION
    lines = [f"- **{name}** — {meaning}" for name, meaning in METRIC_GLOSSARY]
    lines.append("")
    lines.append(f"Scoring: {SCORING_EXPLANATION}")
    return "\n".join(lines)


# ================================================================= README.md


def readme_md(profile_name: str, profile_type: str = "subject",
              subject_context: str = "") -> str:
    context = subject_context.strip() or DEFAULT_SUBJECT_CONTEXT
    year = dt.datetime.now().year
    return f"""{MARKER}
# {profile_name} — recording archive

This folder is the complete record of one person's forearm nerve/muscle
recordings, made with a Mudra Band and an app called Factum.

**It is designed to outlive the app.** Everything here is plain text:
CSV for the signal data, JSON for metadata, Markdown for the writing.
You do not need Factum, or any particular program, to read any of it —
a text editor, Excel, or LibreOffice will open every file. If you have
found this folder in {year + 10} and have no idea what any of it is,
this file is where to start.

## Who this is

{context}

## What was recorded

Three electrodes sit around the forearm and sample about 1000 times per
second. In the data files the columns are always in this order:

| Column      | Meaning                                       |
|-------------|-----------------------------------------------|
| `timestamp` | milliseconds since the start of that recording |
| `ch1`       | ulnar electrode                               |
| `ch2`       | median electrode                              |
| `ch3`       | radial electrode                              |

Values run from -1 to +1 and are raw — nothing has been filtered,
smoothed or rescaled.

A **probe** is one short recording of one attempted movement, usually
30 seconds, named in his own words. A **session** is one visit: all the
probes recorded that day on that arm, kept together in one folder named
for the date and time.

## How to find your way around

- `profile.json` — who this profile is, and which session is open.
- `left/` and `right/` — one folder per arm. They are independent.
- `left/sessions/2026-08-14_1430/` — one visit. Inside it:
  - `REPORT.md` — **start here.** Plain-language summary of what was
    recorded that day, what looked good, what looked bad, what changed
    since the previous session, and what to try next.
  - `probes/` — the raw recordings, one CSV per probe. Every file
    begins with `#` comment lines describing itself.
  - `probes.json` — every probe's metadata and computed metrics in one
    place, if you would rather not open 20 CSVs.
  - `session_notes.md` — what was said and observed at the time.
  - `analysis.json` — every computed number, machine-readable.
- `left/placement_notes.md` — where the band was positioned, over time.
  This matters more than it sounds: the same movement recorded with the
  band 2 cm further up the arm produces a different signal.

## Reading a probe file

Open it in any text editor. The top of the file explains itself:

```
# profile: {profile_name}
# arm: left
# probe: curl ring finger
# started: 2026-08-14T14:33:07
# duration_s: 30
# sample_rate_hz: 1000
# effort: moderate
# fatigue: some
# his_confidence: 4
# filters: none
timestamp,ch1,ch2,ch3
0,0.02310,-0.01502,0.08911
1,0.01903,-0.02011,0.09104
```

`effort`, `fatigue` and `his_confidence` are his own ratings, recorded
at the time: how hard the movement was, how tired it left him, and how
sure he was that he did the same thing on each repetition. They are
subjective on purpose — they are often more predictive of whether a
movement will actually be usable day to day than the signal itself.

If a header says `status: incomplete`, the recording was interrupted
part-way. The data it contains is still valid.

## What the analysis was trying to find

Not the strongest signal — the **smallest set of movements he can
produce the same way every time, without tiring**. A weak movement
performed identically is more useful than a strong one that varies, and
a movement that exhausts him will not survive daily use however good it
looks on paper. The scoring in `REPORT.md` is weighted accordingly.

## A note on the numbers

Every metric is defined in plain language at the bottom of each
`REPORT.md`, and in `CLAUDE.md` next to this file. Nothing is computed
that is not explained somewhere in the folder.
"""


# =================================================================== writing


def write_profile_docs(profile_root: str, profile_name: str,
                       profile_type: str = "subject",
                       subject_context: str = "") -> list:
    """Write CLAUDE.md and README.md. Returns the paths actually written."""
    written = []
    pairs = (
        ("CLAUDE.md", claude_md(profile_name, profile_type, subject_context)),
        ("README.md", readme_md(profile_name, profile_type, subject_context)),
    )
    for name, text in pairs:
        path = os.path.join(profile_root, name)
        if _write(path, text):
            written.append(path)

    # placement/ gets a note explaining what belongs in it, since an
    # empty folder tells a future reader nothing.
    placement = os.path.join(profile_root, "placement")
    os.makedirs(placement, exist_ok=True)
    readme = os.path.join(placement, "README.md")
    if _write(readme, f"""{MARKER}
# Placement references

Photos, marks and measurements that let a helper put the band back in
the same place next time. Anything that answers "where exactly was it?"
belongs here: photos of the arm with the band on, close-ups of pen
marks, a ruler in shot, a diagram.

The same movement recorded with the band 2 cm further up the arm looks
like a different movement. Placement is the single biggest source of
day-to-day variation in this data, which is why it gets its own folder
and its own running log (`left/placement_notes.md`,
`right/placement_notes.md`).

Suggested naming: `2026-08-14_left_markA.jpg` — date first so the
folder sorts chronologically.
"""):
        written.append(readme)
    return written


if __name__ == "__main__":
    import tempfile

    root = os.path.join(tempfile.gettempdir(), "armband-docs-selftest", "kyle")
    os.makedirs(root, exist_ok=True)
    written = write_profile_docs(root, "kyle")
    print("wrote:")
    for p in written:
        print(f"  {os.path.relpath(p, root):<24} {os.path.getsize(p):,} bytes")
    print("\nsecond run (should write nothing):")
    print("  ", write_profile_docs(root, "kyle") or "nothing — already current")

    # Human edit must survive regeneration.
    claude = os.path.join(root, "CLAUDE.md")
    with open(claude, "r", encoding="utf-8") as f:
        body = f.read()
    with open(claude, "w", encoding="utf-8") as f:
        f.write(body.replace(MARKER, "# hand-edited, marker removed"))
    write_profile_docs(root, "kyle")
    with open(claude, "r", encoding="utf-8") as f:
        kept = f.readline().strip()
    print("hand-edited file preserved:", kept == "# hand-edited, marker removed")
    print("OK")
